### ISSUE TITLE
HTML boilerplate dependencies

### ISSUE THREAD

**Issue by rmx90210** [CityOfPhiladelphia/standards-docs#24]
First of all, this site is super helpful! Nice to have an easy reference for the new standards library.

We were testing out using the new HTML boilerplate and found that copying and pasting didn't quite work like it used to with Patterns. A few of the dependencies (`standards.css` and `standards.js`) are sourced with relative paths, so they have to be downloaded and placed in the same folder to work. A few of the vendor libraries (jQuery, Font Awesome) are also throwing 404s.

Not sure if it's already on the roadmap, but it would great if the boilerplate used CDN-hosted files so it could be copied and pasted right into a new project. That's all, thanks!

**Comment by karissademi** [comment]
Thanks, @rbrtmrtn! You raise a good point, and we've been back and forth on this topic internally. On the one hand, it would make the entry point for new projects much lower, but on the other, if want to adopt more modern dev processes, then those dependencies could be pulled in via npm or yarn and incorporated in a build script. 

I think we should leave this issue open, because I think there is value in accommodating both workflows. Thanks for your feedback!

**Comment by rmx90210** [comment]
That makes sense to me. I hadn't seen the Technical Details page when I wrote that ^^, so I think I understand the intended workflow now. This was a quick-and-dirty mockup we were doing so I ended up using unpkg links which worked quite well, but definitely not opposed to npm/yarn for more serious projects. Thanks for clarifying @karissademi!
